#pragma once

#include "../utils/Enums.h"

namespace Coordinates {

  const uint8_t PROGMEM Player[] = {

    11, 121, 74, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    13, 121, 74, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    15, 121, 74, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    17, 120, 73, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    19, 120, 73, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    21, 120, 73, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    23, 120, 73, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    25, 120, 73, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    27, 119, 72, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    29, 119, 72, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    31, 119, 72, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    33, 119, 72, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    35, 119, 72, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    37, 118, 71, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    39, 118, 71, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    41, 118, 71, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    43, 118, 71, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    45, 118, 71, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    47, 117, 70, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    49, 117, 70, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    51, 117, 70, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    53, 117, 70, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    55, 117, 70, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    57, 116, 69, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    59, 116, 69, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    61, 116, 69, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    63, 116, 69, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    65, 116, 69, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    67, 115, 67, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    69, 115, 67, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    71, 115, 67, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    73, 115, 67, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    75, 115, 67, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    77, 114, 66, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    79, 114, 66, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    81, 114, 66, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    83, 114, 66, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    85, 114, 66, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    87, 113, 65, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    89, 113, 65, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),
    91, 113, 65, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Jump),

    // Bottom of first ladder ..
    93, 113, 65, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Left),
    93, 111, 63, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 109, 61, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 107, 59, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 105, 57, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 103, 55, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 101, 53, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 99, 51, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 97, 49, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 95, 47, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 93, 45, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 91, 43, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    93, 89, 41, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Down),
    91, 89, 41, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    89, 88, 40, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    87, 88, 40, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    85, 88, 40, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    83, 88, 40, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    81, 88, 40, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    79, 87, 39, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    77, 87, 39, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    75, 87, 39, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    73, 87, 39, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    71, 87, 39, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    69, 86, 38, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    67, 86, 38, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    65, 86, 38, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    63, 86, 38, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    61, 86, 38, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    59, 85, 37, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    57, 85, 37, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    55, 85, 37, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    53, 85, 37, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    51, 85, 37, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    49, 84, 36, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    47, 84, 36, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    45, 84, 36, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    43, 84, 36, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    41, 84, 36, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    39, 83, 35, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    37, 83, 35, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    35, 83, 35, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    33, 83, 35, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    31, 83, 35, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    29, 82, 34, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    27, 82, 34, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    25, 82, 34, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    23, 82, 34, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    21, 82, 34, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    19, 81, 33, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    17, 81, 33, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    15, 81, 33, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    13, 81, 33, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    11, 81, 33, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Reverse) | static_cast<uint8_t>(Movements::Right) | static_cast<uint8_t>(Movements::Up),
    11, 79, 31, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 77, 29, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 75, 27, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 73, 25, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),

    11, 71, 23, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 69, 21, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 67, 19, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 65, 17, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 63, 15, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 61, 13, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 59, 11, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 57, 9, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 55, 7, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 53, 5, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 51, 3, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 49, 1, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 47, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 45, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 43, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 41, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Up) | static_cast<uint8_t>(Movements::Down),
    11, 39, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Down) | static_cast<uint8_t>(Movements::Right),

    13, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    15, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    17, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    19, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    21, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    23, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    25, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),
    27, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left) | static_cast<uint8_t>(Movements::Right),

    29, 38, 0, 0, static_cast<uint8_t>(Stance::Normal), static_cast<uint8_t>(Movements::Left),

  };
 
}